#!/bin/bash

export USE_CCACHE=1
TIM_FIL=/run/shm/time_ccdroid
YYOUT=/run/shm/outD
export CC=gcc-4.6
export CXX=g++-4.6
#HIDEB=showcommands
HIDEB=

function jjsu {
T0=`tail -2 ${TIM_FIL} |grep Start`
T1=`tail -1 ${TIM_FIL} |grep End`
#echo $T0
#echo $T1
M0=`echo $T0 | sed 's/.*\(..\)$/\1/'`
M1=`echo $T1 | sed 's/.*\(..\)$/\1/'`
F0=`echo $T0 | sed 's/.*\(..\)\(..\)$/\1/'`
F1=`echo $T1 | sed 's/.*\(..\)\(..\)$/\1/'`

if [ "`expr $M1 \< $M0`" = "1" ]; then
  M1=`expr $M1 + 60`
  F1=`expr $F1 - 1`
fi
echo "Spend `expr $F1 - $F0`m `expr $M1 - $M0`s"
}

if [ $# = 1 -a "$1" = "C" ];then
   echo "!!! Clean !!!"
   OUT_DIR=${YYOUT} make clean
   echo -ne "----CLEAN----\n" >> ${TIM_FIL}
   exit 0
elif [ $# = 1 -a "$1" = "S" ];then
   echo "!!! Make -j1 !!!"
   OUT_DIR=${YYOUT} make -j1 showcommands
   exit 0
elif [ $# = 2 -a "$1" = "C" ];then
   echo "!!! Clean module [$2] !!!"
   OUT_DIR=${YYOUT} make clean-$2
   exit 0
elif [ $# = 2 -a "$1" = "M" ];then
   echo "!!! Make a module [$2] !!!"
   OUT_DIR=${YYOUT} make $2 showcommands
   exit 0
else
   #rm -rf ${YYOUT} && mkdir ${YYOUT}
   [ -L ./out ] || ln -sf ${YYOUT} ./out
   echo -ne "Start: `date +%H%M%S`\n" >> ${TIM_FIL}
   OUT_DIR=${YYOUT} make -j16 ${HIDEB}
   echo -ne "End:   `date +%H%M%S`\n" >> ${TIM_FIL}
   jjsu >> ${TIM_FIL}
fi
